-- Create Database and Schemas required
CREATE DATABASE IF NOT EXISTS EMP;
CREATE SCHEMA IF NOT EXISTS EMP.HRDATA;
CREATE SCHEMA IF NOT EXISTS EMP.PROCS;

-- Sample procedure
CREATE OR REPLACE PROCEDURE EMP.PROCS.SP_SAMPLE_PROGRAM("N" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
COMMENT='This is a sample program'
EXECUTE AS CALLER 
AS

BEGIN
    RETURN 'Your Good Name is '||N;
END;

CALL EMP.PROCS.SP_SAMPLE_PROGRAM('Sandeep');


-- Procedure to find square root of a given number
CREATE OR REPLACE PROCEDURE EMP.PROCS.SP_FIND_SQRT("IP_NUMBER" INTEGER)
RETURNS FLOAT
LANGUAGE SQL
COMMENT='This is a sample demo program to find sqrt of the given number'
EXECUTE AS CALLER 
AS

DECLARE
    sqroot FLOAT;
	
BEGIN
    sqroot := SQRT(IP_NUMBER);
    RETURN sqroot;
END;

CALL EMP.PROCS.SP_FIND_SQRT(26397);
CALL EMP.PROCS.SP_FIND_SQRT(625);
